### ISSUE TITLE
missing call esp gadget on Mac OS X

### ISSUE THREAD

**Issue by TakahiroHaruyama** [sashs/Ropper#54]
Hi,

I tried to search "call esp" gadget. It was not found.
On the other hand, I used "ropchain virtualprotect" command then "call esp" gadget found in the gadgets.

(a.exe/PE/x86)> search call esp;
[INFO] Searching for gadgets: call esp;

(a.exe/PE/x86)> ropchain virtualprotect address=0x0056D39Ca

...(skipped)
p = lambda x : pack('I', x)
shellcode = '\xcc'*100
IMAGE_BASE_0 = 0x00400000 # 9f59a606c57217d98a5eea6846c8113aca07b203e0dcf17877b34a8b2308ade6.exe
rebase_0 = lambda x : p(x + IMAGE_BASE_0)

rop = ''
...(skipped)
rop += rebase_0(0x00001bd2) # 0x00401bd2: pop ebp; ret;
rop += rebase_0(0x00023090) # <= VA 0x423090 is "call esp" (I checked it on IDA Pro)
...(skipped)

So the gadget is missing in just search command. Is that bug? 
I use version 1.11.2 on Mac OS X. I installed it from pip.

**Comment by TakahiroHaruyama** [comment]
I found I could reproduce the missing after the command 'type rop'. If the setting 'type all', there is no problem. I'm not sure about the reason.

**Comment by sashs** [comment]
Hi. 
if you use the command "type rop", ropper will only look for rop gadgets. If type has been set to all, ropper looks for rop, jop and syscall gadgets. "call esp" is not a rop gadgets due to the missing ret instruction. It is a jop gadget. That is, if ropper looks only for rop gadgets, it does not list any call reg gadget.

**Comment by TakahiroHaruyama** [comment]
Oh, ok thanks!!
